
#include "rwmake.ch"
/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma ณAGC_NFZEROบAutor ณTOTVS		        บ Data ณ 30/01/2014   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc.     ณ PROGRAMA COMPLETAR NUMERO DA NF DE ENTRA A ESQUERDA        บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
ฑฑบUso       ณ Compilar este fonte e                                      บฑฑ
ฑฑบ			 ณ Colocar no X3_VLDUSER do campo F1_DOC --> U_AGC_NFZERO(9)  บฑฑ
ฑฑบ			 ณ Revisado por Adriano Costa                U_AGC_SRZERO(3)  บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/   

User Function AGC_NFZERO(ntam)
	CNFISCAL := STRZERO(VAL(CNFISCAL),ntam)
Return(.T.)

/*
Notas de Transferencia Filial //
*/
User Function FTRANSF(CTes)
	cTransf := Posicione("SF4",1,xFilial("SF4")+cTes,"F4_TRANSFIL")
	CNFISCAL := substr(CNFISCAL3,6)
Return(.T.)

/*
Notas de Transferencia Filial //
*/
User Function AGC_SRZERO(ntam)
	If CSERIE <> "U"
		CSERIE := STRZERO(VAL(CSERIE),ntam)
	EndIf
Return(.T.)



